### ISSUE TITLE
ms2rescore graphical user interface 

### ISSUE THREAD

**Issue by DaliJarboui** [compomics/ms2rescore#116]
In the latest release, the graphical user interface with a one-click installer for Windows is missing !
I look forward to try the new ms2rescore, for now getting used to MS2Rescore v3.0.0b5 with Maxquant Data.
thanks a lot for all the work you are doing to make those tools available.

**Comment by RalfG** [comment]
Hi,

Thanks for letting us know! Something went wrong during the latest build. I have now manually uploaded the installer. 

Best,
Ralf
