### ISSUE TITLE
Add feature descriptions to documentation

### ISSUE THREAD

**Issue by Guitou1** [compomics/ms2rescore#124]
The generated file containing the weights of features coming from the different feature generators doesn't have any feature description. For MS2PIP mainly, most of the features are not comprehensible by their name only. I've tried looking for the feature descriptions elsewhere, but I couldn't find any.

Would you happen to know of some documentation on that regard ? Could the documentation be updated on the ms2rescore doc. page ? I think that could be a nice addition.

Thank you in advance !

Guillaume D.

**Comment by RalfG** [comment]
Hi Guillaume,

Good point. Most features (especially the MS²PIP ones) are listed in the supplementary information of our 2022 paper: https://ars.els-cdn.com/content/image/1-s2.0-S1535947622000743-mmc1.docx (https://doi.org/10.1016/j.mcpro.2022.100266). However, we should definitely add the full list to the documentation.

Best,
Ralf
