### ISSUE TITLE
Adding peptide n-terminal fixed modification

### ISSUE THREAD

**Issue by XiuyuanChen1** [compomics/ms2rescore#125]
Hi,

Sorry for the bothering, I’m using MS2Rescore to process my MaxQuant data. The fixed modification during the search is TMTpro label, which is on both of the peptide n-term and K. In the MS2Rescore, I added the fixed modification as “U:TMTpro   nterm,K”, the TMTpro on K has been successfully applied but based on the output, it seems like MS2Rescore didn’t apply the n-term TMTpro modification as a fixed modification. Would you mind sharing the correct method to apply the n-term fixed modification in MS2Rescore? 

Thanks!

**Comment by RalfG** [comment]
Hi,

Thanks for your interest in MS²Rescore! I have looked into the issue, and it seems that in our current implementation, fixed terminal modifications could not be added through the configuration file or GUI. This is somewhat related to hupo-psi/proforma#6.

I have implemented a workaround in [psm_utils v0.7.4](https://github.com/compomics/psm_utils/releases/tag/v0.7.4). If you installed MS²Rescore with pip or conda, you can update psm_utils separately, for instance with:

```
pip install -U psm_utils
```

Then, `U:TMTpro` on `K,N-term` should work as expected.

Let us know if this solution works for you.

Best,
Ralf
