### ISSUE TITLE
MSMS Parsing with MaxQuant 

### ISSUE THREAD

**Issue by JesusCastano01** [compomics/ms2rescore#136]
Hi,

I have been trying to do rescoring using the MS2rescore user interface on some MaxQuant results, but I keep getting this error message:

"File "psm_utils\io\maxquant.py", line 98, in _evaluate_columns
    raise MSMSParsingError(
psm_utils.io.maxquant.MSMSParsingError: Missing columns: ['Raw file']"

I'm not sure how to fix this.

Any help would be greatly appreciated.
Thanks,
Jesus

image.png

**Comment by RalfG** [comment]
Hi Jesus,

Most likely it is a file encoding issue. Could you open the MaxQuant file in an editor such as notepad, notepad++, or vscode and save it with `utf-8` as encoding?

For instance, on Windows:

![image](https://github.com/compomics/ms2rescore/assets/26458971/7ffc684e-d77e-4a86-8c0c-8eaf902bf914)

Let us know if that fixes the issue.

Best,
Ralf

---
Potentially related to compomics/psm_utils#68.

**Comment by JesusCastano01** [comment]
Hi,
Thank you. This resolved the issue, and I could start the run. However, it seems that the software now gets stuck in one of the steps, as shown in the figure below. The error where it gets stuck says "Can't pickle local object 'create_engine.<locals>.connect'" 

Do you have any idea about what could fix this issue?


![image](https://github.com/compomics/ms2rescore/assets/139022774/81e101fd-b8d8-46df-ba16-6464d9aaad0b)

**Comment by RalfG** [comment]
Hi @JesusCastano01,

The pickling issue should be fixed in v3.0.3.

Best,
Ralf
