### ISSUE TITLE
Model slowly downloaded

### ISSUE THREAD

**Issue by danyunghsu** [compomics/ms2rescore#139]
Hi all,

I'm using CLI to run MaxQuant psm file.I've been downloading this xgboost model for half an hour and I see no progress.

Can anyone tell if there is something wrong with my settings? 

Thanks in advance,
Danyung
![ms2rescore](https://github.com/compomics/ms2rescore/assets/126338073/c33dfb2b-ed4f-43eb-b48e-7d2f8656de3f)

**Comment by RalfG** [comment]
Hi Danyung,

That is indeed quite slow. How is your internet connection? The file is 847 MB, so on a slow internet connection, that could take a while... You can also download the models manually to the `C:\Users\Lenovo\.ms2pip` directory from the link below. Then MS²PIP should detect the pre-downloaded files automatically.

https://genesis.ugent.be/uvpublicdata/ms2pip/

Best,
Ralf

**Comment by danyunghsu** [comment]
Hi Ralf,

Thanks for the link! I am now able to continue the process.

Danyung
