### ISSUE TITLE
Could not find matching spectra

### ISSUE THREAD

**Issue by JesusCastano01** [compomics/ms2rescore#140]
Hi,
I've been trying to run MS2Rescore from the Command Line, and I ran into an issue. I'm using MaxQuant search results, and it looks like I have to specify something for the parameters below, which are currently set at "null."

"psm_id_pattern": null,
"spectrum_id_pattern": null,

I've checked the documentation, but I haven't been able to find a solution to this. There's an example for MGF, but not for MaxQuant. 
Do you have any ideas about how to solve this problem?

I'd appreciate any advice.

![image](https://github.com/compomics/ms2rescore/assets/139022774/f0461d00-36e6-467a-a5fb-886699168abd)

This is what my config.json file looks like, just in case it's useful.

![image](https://github.com/compomics/ms2rescore/assets/139022774/cd6be548-d5c7-4b12-9f64-97c1c69e31bf)

**Comment by RalfG** [comment]
Hi @JesusCastano01,

You will indeed have to set one (or both) of those settings. Could you share the top of the MaxQuant msms.txt file and a section of an mzML file that contains a spectrum header? Depending on what the spectra are named in both files, we need to set regular expression patterns to match the two to each other.

Best,
Ralf

**Comment by RalfG** [comment]
Relevant documentation: https://ms2rescore.readthedocs.io/en/stable/userguide/configuration/#mapping-psms-to-spectra
