### ISSUE TITLE
Scipy dependency issue in Windows Installer for v3.0.3

### ISSUE THREAD

**Issue by RalfG** [compomics/ms2rescore#145]
> Hi, ralph
> Hope you are doing well,
> 
> First, since I was testing your windows installation to make a protocol for a gui user, things like pip are not used. 
> 
> Now, I just tried reinstalling the .exe file for version 3.0.3 and the program wont open after the installation for me to retest everything and give you more info
> heres the error i encounter right now'
> 
> ![image](https://github.com/compomics/ms2rescore/assets/105518103/840d17ab-9426-402d-b52f-b6a6d4d34bde)
> 
> if i scroll at the end i see
> 
> <details>
>   <summary>Click to expand</summary>
>   
>   
>    ` Traceback (most recent call last):
>   File "ms2rescore\gui\__main__.py", line 7, in <module>
>     from ms2rescore.gui.app import app
>   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
>   File "ms2rescore\__init__.py", line 16, in <module>
>     from ms2rescore.core import rescore  # noqa: F401 E402
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
>   File "ms2rescore\core.py", line 9, in <module>
>     from ms2rescore.feature_generators import FEATURE_GENERATORS
>   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
>   File "ms2rescore\feature_generators\__init__.py", line 9, in <module>
>     from ms2rescore.feature_generators.ms2pip import MS2PIPFeatureGenerator
>   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
>   File "ms2rescore\feature_generators\ms2pip.py", line 34, in <module>
>     from ms2pip import correlate
>   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
>   File "ms2pip\__init__.py", line 13, in <module>
>     from ms2pip.core import (  # noqa: F401 E402
>   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
>   File "ms2pip\core.py", line 25, in <module>
>     from ms2pip._utils.xgb_models import get_predictions_xgb, validate_requested_xgb_model
>   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
>   File "ms2pip\_utils\xgb_models.py", line 10, in <module>
>     import xgboost as xgb
>   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
>   File "xgboost\__init__.py", line 7, in <module>
>     from . import collective, dask, rabit
>   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
>   File "xgboost\dask.py", line 77, in <module>
>     from .sklearn import (
>   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
>   File "xgboost\sklearn.py", line 22, in <module>
>     from scipy.special import softmax
>   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
>   File "scipy\special\__init__.py", line 777, in <module>
>   File "scipy\\special\\_ufuncs.pyx", line 1, in init scipy.special._ufuncs
> ModuleNotFoundError: No module named 'scipy.special._cdflib'`
> </details>
> 
> 
> If youd like me to open a different issue for this particuliar issue, just ask
> 
> If testing and fixing the windows gui version isnt a priority right now I am ok to wait until it is
> 
> Thanks  a lot

_Originally posted by @NicolasProvencher in https://github.com/compomics/ms2rescore/issues/108#issuecomment-2043214323_

**Comment by RalfG** [comment]
Issue was caused by a change from Scipy 1.12 to 1.13 and PyInstaller not being updated yet. A fix should be included in the next PyInstaller release (https://github.com/pyinstaller/pyinstaller/commit/5fe069177c9fda8ae7e362cdaa5b39c5b64fe4f5).

**Comment by NicolasProvencher** [comment]
Hi issue seems to be fixed so closing this issue.
For the deeplc analysis i am starting a run, I will update its issue soon

Thanks for the help :)
