### ISSUE TITLE
error running rescore - tries to download something?

### ISSUE THREAD

**Issue by Dmorgen** [compomics/ms2rescore#147]
Hi, running rescore on Sage results, the program crashed trying to download something? our servers are disconnected from the web, so we can't have software connecting to the outside.

![image](https://github.com/compomics/ms2rescore/assets/35773089/fa156ff5-1ad9-48ce-81fd-abd2ef187807)
![image](https://github.com/compomics/ms2rescore/assets/35773089/4f1625e4-2610-49bf-8c97-18e71152250b)

Thanks!
David

**Comment by prvst** [comment]
My network is stopping ms2rescore from doing these requests. Are there any explanations as to why this is happening and how to avoid it in the future?

**Comment by paretje** [comment]
The ms2pip models using xgboost aren't included with the package, but downloaded at runtime. They are stored in the `.ms2pip` folder, in your case `C:\Users\pmdavid\.ms2pip`. You'll need to download https://genesis.ugent.be/uvpublicdata/ms2pip/model_20210416_HCD2021_B.xgboost and https://genesis.ugent.be/uvpublicdata/ms2pip/model_20210416_HCD2021_Y.xgboost. If you put those files in the `.ms2pip` folder on that server using e.g. a USB stick, it should work.

If you want be sure all models are available on that server, these are the others:
 - https://genesis.ugent.be/uvpublicdata/ms2pip/model_20190107_CID_train_B.xgboost
 - https://genesis.ugent.be/uvpublicdata/ms2pip/model_20190107_CID_train_Y.xgboost
 - https://genesis.ugent.be/uvpublicdata/ms2pip/model_20190107_TTOF5600_train_B.xgboost
 - https://genesis.ugent.be/uvpublicdata/ms2pip/model_20190107_TTOF5600_train_Y.xgboost
 - https://genesis.ugent.be/uvpublicdata/ms2pip/model_20190107_iTRAQ_train_B.xgboost
 - https://genesis.ugent.be/uvpublicdata/ms2pip/model_20190107_iTRAQ_train_Y.xgboost
 - https://genesis.ugent.be/uvpublicdata/ms2pip/model_20190107_iTRAQphospho_train_B.xgboost
 - https://genesis.ugent.be/uvpublicdata/ms2pip/model_20190107_iTRAQphospho_train_Y.xgboost
 - https://genesis.ugent.be/uvpublicdata/ms2pip/model_20190107_CID_train_B.xgboost
 - https://genesis.ugent.be/uvpublicdata/ms2pip/model_20190107_CID_train_Y.xgboost
 - https://genesis.ugent.be/uvpublicdata/ms2pip/model_20190107_CID_train_B2.xgboost
 - https://genesis.ugent.be/uvpublicdata/ms2pip/model_20190107_CID_train_Y2.xgboost
 - https://genesis.ugent.be/uvpublicdata/ms2pip/model_20210316_Immuno_HCD_B.xgboost
 - https://genesis.ugent.be/uvpublicdata/ms2pip/model_20210316_Immuno_HCD_Y.xgboost
 - https://genesis.ugent.be/uvpublicdata/ms2pip/model_20220104_CID_TMT_B.xgboost
 - https://genesis.ugent.be/uvpublicdata/ms2pip/model_20220104_CID_TMT_Y.xgboost
 - https://genesis.ugent.be/uvpublicdata/ms2pip/model_20230912_timsTOF_B.xgboost
 - https://genesis.ugent.be/uvpublicdata/ms2pip/model_20230912_timsTOF_Y.xgboost
 - https://genesis.ugent.be/uvpublicdata/ms2pip/model_20240105_timsTOF_B.xgboost
 - https://genesis.ugent.be/uvpublicdata/ms2pip/model_20240105_timsTOF_Y.xgboost
