### ISSUE TITLE
Target-decoy competition settings

### ISSUE THREAD

**Issue by MatteoLacki** [compomics/ms2rescore#153]
Hi,

I have navigated the docs a bit and cannot find any passage about what options does one have when it comes to using target-decoy competition. What strategy is used by default? How can one modify the target FDR filter value from the standard 1%? 

Best wishes,
Matteo Lacki

**Comment by RalfG** [comment]
Hi Matteo,

Thanks for the questions. The documentation will be updated for the next version to include more concrete info TDC and FDR.

### Target decoy competition (TDC)

When using Mokapot as rescoring engine, I believe only TDC (PSMs from a concatenated search) is supported. When using Percolator, we enable the `post-processing-tdc` flag by default, assuming PSMs coming from a concatenated search. This flag can be disabled within the `rescoring_engine` > `percolator` configuration.

While we have not tested MS²Rescore with PSMs from separate target and decoy searches, the principle of adding more rescoring features should work in the same way. If the rescoring engine can be configured properly (in this case only Percolator), I do not foresee any technical issues.

### FDR filtering

MS²Rescore does not perform any filtering on its output (except for the PSM rank filter that is coming in v3.1.0). It reports PSMs from both target and decoy PSMs, regardless of q-value. FDR levels for rescoring can be configured through the individual rescoring engine configurations.

Best,
Ralf
