### ISSUE TITLE
SSL certificate error

### ISSUE THREAD

**Issue by prvst** [compomics/ms2rescore#170]
Hello, I get an SSL certificate error when trying to run the program, most probably from my network. Does ms2rescore send or receive data from other servers? Can this be disabled?

```
 ERROR    ms2rescore.__main__ // <urlopen error [SSL:        
                             CERTIFICATE_VERIFY_FAILED] certificate verify      
                             failed: self-signed certificate in certificate     
                             chain (_ssl.c:1006)>
```

**Comment by paretje** [comment]
ms2pip downloads it's models at runtime. As noted in https://github.com/compomics/ms2rescore/issues/147#issuecomment-2275628776, you can download those models yourself in advance, and put them in the `.ms2pip` folder.

I assume that's where this error occurs, although the self-signed certificate error is a bit strange. But I see the URL uses http (with a redirect to https server-side), so it might be intercepted locally.

**Comment by prvst** [comment]
Thanks, @paretje. Do you know where these files go if I build a container with the pip install command?

**Comment by RalfG** [comment]
In a container, it would also go to the `~/.ms2pip` directory. To avoid model downloads for each newly created container, you could mount `~/.ms2pip` to an external volume.

**Comment by prvst** [comment]
Thanks
