### ISSUE TITLE
'charmap' codec can't encode characters in position XX

### ISSUE THREAD

**Issue by JesusCastano01** [compomics/ms2rescore#183]
Hi,

I've been trying to use MS2Rescore with some results from MaxQuant, and I can't seem to get it to run successfully. I've tried different release versions, and I always run into an issue. I used it before successfully, but now, I haven't found a way to run it.

The current error message says:

 **UnicodeEncodeError: 'charmap' codec can't encode characters in position 18-20: character maps to <undefined>**

It looks like an encoding problem, but the msms file encoding is UTF-8 already, so I'm not sure.

I'm attaching the log file and json file, just in case.
I used ms2rescore 3.0.2 and also the latest version, and with both of them, I had the same issue.

I appreciate any advice on this.

Thanks,

[CLI_test_percolator-config.json](https://github.com/user-attachments/files/16701165/CLI_test_percolator-config.json)
[ms2rescore_out_percolator.log.txt](https://github.com/user-attachments/files/16701166/ms2rescore_out_percolator.log.txt)

**Comment by RalfG** [comment]
Hi @JesusCastano01,

Thanks for reaching out! This is a very peculiar one... Would you also be able to share the input file? On first glance, the configuration file looks fine.

Best,
Ralf

**Comment by JesusCastano01** [comment]
Hi Ralf,
Unfortunately, the input file is bigger than the allowed 25 MB. Any other way I can share the msms input file with you?

**Comment by RalfG** [comment]
Hi @JesusCastano01,

This was most-likely the same issue as in #185, which is now fixed in [v3.1.2](https://github.com/compomics/ms2rescore/releases/tag/v3.1.2). 

Best,
Ralf
