### ISSUE TITLE
num_cpus used by MS2PIP

### ISSUE THREAD

**Issue by tivdnbos** [compomics/ms2rescore#25]
MS2PIP takes the default of 8 CPUs instead of taking the user defined option in config file

2021-02-05 08:57:40 // INFO // numexpr.utils // Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2021-02-05 08:57:40 // INFO // numexpr.utils // NumExpr defaulting to 8 threads.

**Comment by tivdnbos** [comment]
Update: num_cpus should read "-1" as all available (positive integers currently work).

**Comment by RalfG** [comment]
This is a DeepLC/TensorFlow issue, not MS²PIP/MS²ReScore. Opened a new issue here: https://github.com/compomics/DeepLC/issues/19#issue-803484251

`-1` should already be converted to all available CPUs:
https://github.com/compomics/ms2rescore/blob/67d5b819e150c422a7ffb2bada19a93936dbd960/ms2rescore/config_parser.py#L102-L109
