### ISSUE TITLE
[Bug] Use Percolator protein-decoy-pattern to generate pin files if provided by user

### ISSUE THREAD

**Issue by tivdnbos** [compomics/ms2rescore#26]
For Tandem pipeline, "REVERSED" is used as default while "decoy_" is specified by user.

**Comment by RalfG** [comment]
`id_decoy_pattern` is already an option. Does it work for your usecase?
https://github.com/compomics/ms2rescore/blob/master/configuration.md#properties

**Comment by tivdnbos** [comment]
Yep, that works!
