### ISSUE TITLE
Failed to install ms2rescore

### ISSUE THREAD

**Issue by Peer2011** [compomics/ms2rescore#38]
Dear Ralf, 
I would love to test ms2rescore in conjunction with FragPipe. However, I failed to install it with the Anaconda prompt. The following error code is shown. Maybe you have an idea how to solve this issue. Thanks for your help. 

Best, Peer 

  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\gu68nur\AppData\Local\Temp\pip-build-env-9_7v_9p0\overlay\Lib\site-packages\numpy\core\include -IC:\01_ScientificSoftware\Anaconda\include -IC:\01_ScientificSoftware\Anaconda\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcms2pip/cython_modules\ms2pip_pyx.c /Fobuild\temp.win-amd64-3.8\Release\ms2pip/cython_modules\ms2pip_pyx.obj -fno-var-tracking -Og -Wno-unused-result -Wno-cpp -Wno-unused-function
  cl : Befehlszeile warning D9035 : Die Option "Og" ist veraltet und wird in einer der n„chsten Versionen entfernt.
  cl : Befehlszeile error D8021 : Ung\x81ltiges numerisches Argument /Wno-unused-result.
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for ms2pip
Failed to build ms2pip
ERROR: Could not build wheels for ms2pip which use PEP 517 and cannot be installed directly

**Comment by RalfG** [comment]
Hi @Peer2011,

Previous versions of MS²PIP did not run on Windows. As of [v3.8.0](https://github.com/compomics/ms2pip_c/releases/tag/v3.8.0) we do support Windows! Can you first try `pip install ms2pip==3.8.0` and then `pip install ms2rescore`?

Best,
Ralf

**Comment by RalfG** [comment]
We will also release a new version of MS²Rescore very soon, including some new features (including a GUI) and numerous fixes.
