### ISSUE TITLE
GUI Windows installation error

### ISSUE THREAD

**Issue by nh2tran** [compomics/ms2rescore#52]
Hello, I'm trying to install the GUI Windows but I got the following error:

`ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\hieutran1985\\Downloads\\ms2rescore-gui-windows\\gui-windows\\Miniconda3\\envs\\ms2rescore\\Lib\\site-packages\\tensorflow\\include\\external\\cudnn_frontend_archive\\_virtual_includes\\cudnn_frontend\\third_party\\cudnn_frontend\\include\\cudnn_frontend_EngineConfig.h'`

It seems related to tensorflow and cudnn.

**Comment by ArthurDeclercq** [comment]
Hi @nh2tran,

This seems to be an long install path issue. By default Windows has a limit on how long a folder/filepath can be (typically 260 char). That is probably why the packages cannot be installed. You could try to install MS²Rescore in a different path to shorten the install path, however, this should already be in the Users path to function. Another workaround could be to enable long install paths in windows registry. Run regedit.exe > navigate to Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem > right-click the space on the right side > select LongPathsEnabled > open it up and change the value data to 1. Restart the computer and try to install the app again, as was suggested here (https://answers.microsoft.com/en-us/windows/forum/all/system-path-may-be-too-long-can-i-safely-change-it/0a011879-ce48-478b-8329-d895776bea6a)

We'll look further into this issue on our side as well.

Hope this helps,
Arthur

**Comment by nh2tran** [comment]
I followed your suggestion and the installation was completed successfully. Thanks a lot!
Hieu
