### ISSUE TITLE
Proteome Discoverer node / PSM file support

### ISSUE THREAD

**Issue by rolivella** [compomics/ms2rescore#73]
Hello! I would like to ask if you are planning to make a Proteome Discoverer node for you tool. It would be very usefull for our facility and I think that for the entire community. Thanks!

**Comment by RalfG** [comment]
Hi, @rolivella,

Happy to announce that ProteomeDiscoverer MSF files are now supported in MS²Rescore 3.0. Exported mzIdentML files should also work.

Let us know how it works out for you!

Ralf

**Comment by rolivella** [comment]
@RalfG thanks! I'll try it and let youb know!
