### ISSUE TITLE
Filtering of PSMs from MaxQuant Search

### ISSUE THREAD

**Issue by jamc1996** [compomics/ms2rescore#74]
Hello,

I noticed that MS2Rescore filters PSMs with duplicate scan IDs from MaxQuant search results as "non-rank 1 PSMs" but to my understanding MaxQuant reports multiple PSMs for chimeric spectra and so filtering these PSMs seems incorrect. Is it possible to configure MS2Rescore to avoid this?

Just wanted to clarify this, thank you for your help.

Best wishes,
John.

**Comment by RalfG** [comment]
Hi John,

Unfortunately, it is an implementation limitation of MS²PIP to only process a single peptide per spectrum in the MGF file. Nevertheless, we are currently working on a major refactoring of the MS²Rescore code, so we may be able to fix this issue in the process.

Best,
Ralf

**Comment by RalfG** [comment]
Closing in favor of #83 (same feature request
