### ISSUE TITLE
PTM information is lost in pin and pout

### ISSUE THREAD

**Issue by caetera** [compomics/ms2rescore#81]
Hi,

it looks like the PTM information is lost in the PIN file produced by ms2rescore. PEPREC has a column with PTMS, but the PIN contains already just plain (stripped) peptide sequences and so does (obviously) the output. I wonder, is there any reason to strip the PTMs from the sequences or is it just a bug?

I believe PIN preserves `SpecId` from PEPREC, and, thus, one can "restore" PTMs if necessary, but I believe it would be much better if PTMs will be preserved in the output by default.

**Comment by RalfG** [comment]
Hi @caetera, Happy to say that this is now fixed in v3.0 of MS²Rescore.
