### ISSUE TITLE
Suggest correction for comet pin file

### ISSUE THREAD

**Issue by progistar** [compomics/ms2rescore#86]
Hello,

First of all, thank you for maintaining this nice software.
I leave some comments for more comprehensive manuals (for comet pin).

1. Change below code. When I applied below, it works well for comet pin file also.

> id_file_parser.py
> line number 46~48
> change "retention_times[index] = float(line[12:].strip())" to "retention_times[titles[index]] = float(line[12:].strip())"

2. Please add explicit explanation about that the column name "lnExpect" must be changed to "COMET:lnExpect" to avoid "psm_score" null point error.

I am glad to share this information with future users ^^*.

**Comment by RalfG** [comment]
Hi @progistar,

Thank you for sharing! We have just released a new beta for MS²Rescore 3.0, which now uses `psm_utils` for reading PSM files, such as PIN. It should be a lot more robust towards parsing issues such as the one you mentioned.

Definitely let us know when you run into any other issues.

Thanks!
