### ISSUE TITLE
issue with installation

### ISSUE THREAD

**Issue by Parniyan-M** [compomics/ms2rescore#93]
Hi, I am trying to install ms2rescore but there is an issue with installation. i get these errors and when i want to start the gui, the command window comes for 0.2 seconds and disappears and nothing gets started. my system already had anaconda, and i tried installing miniconda seperately as well and tried uninstalling everything. nothing changed the outcome!
![Screenshot 2023-08-23 083509](https://github.com/compomics/ms2rescore/assets/142500015/37863c47-849d-48cf-8291-dc5cdedff6fa)

**Comment by XiuyuanChen1** [comment]
Hi,
I also met the same problem. Please open the .bat file with Notepad, and change the encoding method from UTF-8 to ANSI when you save the file. The .bat file works fine after these steps on my computer.
Hope this can help.

**Comment by RalfG** [comment]
Hi @Parniyan-M,

I hope @XiuyuanChen1's suggestion fixed your issue. I also highly recommend to try out the new beta version of MS²Rescore 3.0. It has a completely rebuilt desktop application and a much simpler installation process. 

https://github.com/compomics/ms2rescore/releases/tag/v3.0.0b4

Let us know if you would run into any other issues.

Best,
Ralf
