### ISSUE TITLE
MS-GF+ms2rescore pipeline doesn't run

### ISSUE THREAD

**Issue by Hassan-1991** [compomics/ms2rescore#94]
Dear Concern,

When I try to run ms2rescore on .mzid files generated by MS-GF+, I get the following error:

```
ms2rescore -c ms2rescore_config.json -m test.mgf test.mzid
2023-08-21 14:35:35 // INFO // ms2rescore // Using MSGFPipeline.
2023-08-21 14:36:28 // ERROR // ms2rescore.__main__ // Critical error occured in MS2ReScore
Traceback (most recent call last):
  File "/path/ms2rescore/__main__.py", line 15, in main
    rescore.run()
  File "/path/ms2rescore/__init__.py", line 233, in run
    peprec = self.pipeline.get_peprec()
  File "/path/ms2rescore/id_file_parser.py", line 245, in get_peprec
    return self.peprec_from_pin()
  File "/path/id_file_parser.py", line 191, in peprec_from_pin
    raise IDFileParserError(
ms2rescore.id_file_parser.IDFileParserError: Could not map all MGF retention times to spectrum indices.
```

I understand this topic has been previously discussed on [here](https://github.com/compomics/ms2rescore/issues/79), with the solution being to downgrade to ms2rescore version 2.0.0. But when I run pip install ms2rescore, I get this error:

```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement ms2rescore==2.0.0 (from versions: none)
ERROR: No matching distribution found for ms2rescore==2.0.0
```

The same error occurs when I run just "pip install ms2rescore" a well.

Will be grateful for your help in this regard!

Thanks and best regards,
Hassan

**Comment by RalfG** [comment]
Hi Hassan, 

Thank you for reaching out! I apologize for the long delay in my reply. 

We have just released a new beta version for MS²Rescore 3.0, which is much-improved. You can install it with:

```sh
pip install ms2rescore --pre
```

Also note that at least Python 3.8 is required for MS²Rescore. From your logs, it seems that you were using Python 2.7.

Let me know if this fixes your issues!
