### ISSUE TITLE
Config file for maxquant example in v3.0.0-dev4

### ISSUE THREAD

**Issue by veitveit** [compomics/ms2rescore#98]
We are trying to run the maxquant example in the development version but get an error when running it without config file or with this one: https://github.com/compomics/ms2rescore/blob/main/examples/maxquant-ms2rescore.toml

Is there a config file that works or what are we doing wrong?

**Comment by RalfG** [comment]
Hi Veit,

Could you provide some more details on the errors that you are getting? You can always mail me the log. That might speed up the debugging.
Note that the example uses the old MaxQuant modification labels (e.g., `ox` instead of `Oxidation (M)`).
